print('What is your name?')
name = input()
print('How old are you?')
old = input()
print('Where are you live?')
place = input()
print('This is ', name)
print('It ts ', old)
print('(S)he live in ', place)
