print('Enter 2 numbers')
one = input()
two = input()
f = int(one) + int(two)
a = int(one) - int(two)
c = int(one) * int(two)
print('Сумма ', int(one), '+',int(two),'= ',f)
print('Разность ', int(one), '-',int(two),'= ',a)
print('Произведение ',int(one),'*',int(two),'=',c)
